package com.example.BookShelf.dto;

public enum ErrorCode {
    BOOK_NOT_FOUND,
    BOOK_ALREADY_EXISTS,
    BOOK_NOT_AVAILABLE,
    BOOK_NOT_ISSUED,
    BOOK_NOT_ISSUED_TO_USER,

    CATEGORY_NOT_FOUND,

    USER_NOT_FOUND,
    USER_ALREADY_EXISTS,
    USER_NOT_ISSUED_ANY_BOOK,
    USER_HAS_ALREADY_ISSUED_A_BOOK,
    USER_HAS_ALREADY_ISSUED_A_BOOK_AND_CANNOT_ISSUE_MORE,
    USER_HAS_ALREADY_ISSUED_A_BOOK_AND_CANNOT_ISSUE_MORE_UNTIL_RETURNED,
    USER_HAS_ALREADY_ISSUED_A_BOOK_AND_CANNOT_ISSUE_MORE_UNTIL_RETURNED_AND_CANNOT_ISSUE_MORE_UNTIL_RETURNED,
    USER_HAS_ALREADY_ISSUED_A_BOOK_AND_CANNOT_ISSUE_MORE_UNTIL_RETURNED_AND_CANNOT_ISSUE_MORE_UNTIL_RETURNED_AND_CANNOT_ISSUE_MORE_UNTIL_RET
}
