version: '3.7'

services:
  redisdb:
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - shared-net

  mysqldb:
    image: mysql:8
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: bookshelf
        MYSQL_PASSWORD: root
    ports:
        - "3306:3306"
    networks:
        - shared-net
    volumes:
      - ./mysql-data:/backup

  app:
    image: app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
        - "8080:8080"
    depends_on:
      - mysqldb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/bookshelf?useSSL=false&serverTimezone=UTC
      - SERVER_PORT=8080
      - REDIS_HOST=redisdb
      - REDIS_PORT=6379
    restart: always

networks:
  shared-net:
    driver: bridge